channels:
  - openbabel
  - rdkit
  - anaconda
  - conda-forge
  - e3sm
  - eumetsat
  - schrodinger
  - pytorch
dependencies:
  - python==3.7.*
  - pytorch==1.4.0
  - torchvision==0.5.0
  - cudatoolkit==10.1.*
  - click==7.0.*
  - numpy==1.15.*
  - openbabel==2.4.*
  - pandas==0.24.*
  - scipy==1.4.*
  - path.py==11.5.*
  - griddataformats==0.5.*
  - treelib==1.5.*
  - mdtraj==1.9.*
  - Cython==0.29.*
  - networkx==2.4.*
  - tqdm==4.38.*
  - scikit-learn==0.21.*
  - jupyter==1.0.* # this should not be necessary in the future
  - biopython==1.74.*
  - pymol==2.3.*
  - matplotlib
  - seaborn
  - pytest==5.2.*

