# This code is entirely taken from GradDock source

l_aa = 'ALA ARG ASN ASP CYS GLN GLU GLY HID HIE ILE LEU LYS MET PHE PRO SER THR TRP TYR VAL'.split()

d_aaid = {x: i for i, x in enumerate(l_aa)}

d_1aa = {'SER': 'S', 'LYS': 'K', 'PRO': 'P', 'ALA': 'A', 'ASP': 'D', 'ARG': 'R', 'VAL': 'V', 'CYS': 'C', 'HIS': 'H',
         'ASX': 'B', 'PHE': 'F', 'MET': 'M', 'LEU': 'L', 'ASN': 'N', 'TYR': 'Y', 'ILE': 'I', 'GLN': 'Q', 'THR': 'T',
         'GLX': 'Z', 'GLY': 'G', 'TRP': 'W', 'GLU': 'E'}

d_3aa = {'A': 'ALA', 'C': 'CYS', 'B': 'ASX', 'E': 'GLU', 'D': 'ASP', 'G': 'GLY', 'F': 'PHE', 'I': 'ILE', 'H': 'HIS',
         'K': 'LYS', 'M': 'MET', 'L': 'LEU', 'N': 'ASN', 'Q': 'GLN', 'P': 'PRO', 'S': 'SER', 'R': 'ARG', 'T': 'THR',
         'W': 'TRP', 'V': 'VAL', 'Y': 'TYR', 'Z': 'GLX'}

dihed_count = {'CYS': 1, 'ASP': 2, 'SER': 1, 'GLN': 3, 'LYS': 4, 'ILE': 2, 'PRO': 1, 'THR': 1, 'PHE': 2, 'ALA': 0,
               'GLY': 0, 'HIS': 2, 'GLU': 3, 'LEU': 2, 'ARG': 4, 'TRP': 2, 'VAL': 1, 'ASN': 2, 'TYR': 2, 'MET': 3}

# standard(?) PDB order.
# NOTE: terminal OXT is not listed.
residue_atoms_noh = {
    'GLY': ('N', 'CA', 'C', 'O'),
    'ALA': ('N', 'CA', 'C', 'O', 'CB'),
    'CYS': ('N', 'CA', 'C', 'O', 'CB', 'SG'),
    'SER': ('N', 'CA', 'C', 'O', 'CB', 'OG'),
    'MET': ('N', 'CA', 'C', 'O', 'CB', 'CG', 'SD', 'CE'),
    'LYS': ('N', 'CA', 'C', 'O', 'CB', 'CG', 'CD', 'CE', 'NZ'),
    'ARG': ('N', 'CA', 'C', 'O', 'CB', 'CG', 'CD', 'NE', 'CZ', 'NH1', 'NH2'),
    'GLU': ('N', 'CA', 'C', 'O', 'CB', 'CG', 'CD', 'OE1', 'OE2'),
    'GLN': ('N', 'CA', 'C', 'O', 'CB', 'CG', 'CD', 'OE1', 'NE2'),
    'ASP': ('N', 'CA', 'C', 'O', 'CB', 'CG', 'OD1', 'OD2'),
    'ASN': ('N', 'CA', 'C', 'O', 'CB', 'CG', 'OD1', 'ND2'),
    'LEU': ('N', 'CA', 'C', 'O', 'CB', 'CG', 'CD1', 'CD2'),
    'HIS': ('N', 'CA', 'C', 'O', 'CB', 'CG', 'ND1', 'CD2', 'CE1', 'NE2'),
    'PHE': ('N', 'CA', 'C', 'O', 'CB', 'CG', 'CD1', 'CD2', 'CE1', 'CE2', 'CZ'),
    'TYR': ('N', 'CA', 'C', 'O', 'CB', 'CG', 'CD1', 'CD2', 'CE1', 'CE2', 'CZ', 'OH'),
    'TRP': ('N', 'CA', 'C', 'O', 'CB', 'CG', 'CD1', 'CD2', 'NE1', 'CE2', 'CE3', 'CZ2', 'CZ3', 'CH2'),
    'VAL': ('N', 'CA', 'C', 'O', 'CB', 'CG1', 'CG2'),
    'THR': ('N', 'CA', 'C', 'O', 'CB', 'OG1', 'CG2'),
    'ILE': ('N', 'CA', 'C', 'O', 'CB', 'CG1', 'CG2', 'CD1'),
    'PRO': ('N', 'CA', 'C', 'O', 'CB', 'CG', 'CD'),
}

# listing non-terminal residue; proline gets no backbone hydrogen!
residue_atoms_gromos = {
    'ALA': ('N', 'CA', 'C', 'O', 'H', 'CB'),
    'ARG': ('N', 'CA', 'C', 'O', 'H', 'CB', 'CG', 'CD', 'NE', 'HE', 'CZ', 'NH1', 'HH11', 'HH12', 'NH2', 'HH21', 'HH22'),
    'ASN': ('N', 'CA', 'C', 'O', 'H', 'CB', 'CG', 'OD1', 'ND2', 'HD21', 'HD22'),
    'ASP': ('N', 'CA', 'C', 'O', 'H', 'CB', 'CG', 'OD1', 'OD2'),
    'CYS': ('N', 'CA', 'C', 'O', 'H', 'CB', 'SG', 'HG'),
    'GLN': ('N', 'CA', 'C', 'O', 'H', 'CB', 'CG', 'CD', 'OE1', 'NE2', 'HE21', 'HE22'),
    'GLU': ('N', 'CA', 'C', 'O', 'H', 'CB', 'CG', 'CD', 'OE1', 'OE2'),
    'GLY': ('N', 'CA', 'C', 'O', 'H'),
    'HID': ('N', 'CA', 'C', 'O', 'H', 'CB', 'CG', 'ND1', 'HD1', 'CD2', 'HD2', 'CE1', 'HE1', 'NE2'),
    'HIE': ('N', 'CA', 'C', 'O', 'H', 'CB', 'CG', 'ND1', 'CD2', 'HD2', 'CE1', 'HE1', 'NE2', 'HE2'),
    'ILE': ('N', 'CA', 'C', 'O', 'H', 'CB', 'CG1', 'CG2', 'CD1'),
    'LEU': ('N', 'CA', 'C', 'O', 'H', 'CB', 'CG', 'CD1', 'CD2'),
    'LYS': ('N', 'CA', 'C', 'O', 'H', 'CB', 'CG', 'CD', 'CE', 'NZ', 'HZ1', 'HZ2', 'HZ3'),
    'MET': ('N', 'CA', 'C', 'O', 'H', 'CB', 'CG', 'SD', 'CE'),
    'PHE': ('N', 'CA', 'C', 'O', 'H', 'CB', 'CG', 'CD1', 'HD1', 'CD2', 'HD2', 'CE1', 'HE1', 'CE2', 'HE2', 'CZ', 'HZ'),
    'PRO': ('N', 'CA', 'C', 'O', 'CB', 'CG', 'CD'),
    'SER': ('N', 'CA', 'C', 'O', 'H', 'CB', 'OG', 'HG'),
    'THR': ('N', 'CA', 'C', 'O', 'H', 'CB', 'OG1', 'HG1', 'CG2'),
    'TRP': (
    'N', 'CA', 'C', 'O', 'H', 'CB', 'CG', 'CD1', 'HD1', 'CD2', 'NE1', 'HE1', 'CE2', 'CE3', 'HE3', 'CZ2', 'HZ2', 'CZ3',
    'HZ3', 'CH2', 'HH2'),
    'TYR': (
    'N', 'CA', 'C', 'O', 'H', 'CB', 'CG', 'CD1', 'HD1', 'CD2', 'HD2', 'CE1', 'HE1', 'CE2', 'HE2', 'CZ', 'OH', 'HH'),
    'VAL': ('N', 'CA', 'C', 'O', 'H', 'CB', 'CG1', 'CG2'),
}

residue_atoms_amber = {
    'ALA': ('N', 'CA', 'C', 'O', 'H', 'HA', 'CB', 'HB1', 'HB2', 'HB3'),
    'ARG': (
    'N', 'CA', 'C', 'O', 'H', 'HA', 'CB', 'HB1', 'HB2', 'CG', 'HG1', 'HG2', 'CD', 'HD1', 'HD2', 'NE', 'HE', 'CZ', 'NH1',
    'HH11', 'HH12', 'NH2', 'HH21', 'HH22'),
    'ASN': ('N', 'CA', 'C', 'O', 'H', 'HA', 'CB', 'HB1', 'HB2', 'CG', 'OD1', 'ND2', 'HD21', 'HD22'),
    'ASP': ('N', 'CA', 'C', 'O', 'H', 'HA', 'CB', 'HB1', 'HB2', 'CG', 'OD1', 'OD2'),
    'CYS': ('N', 'CA', 'C', 'O', 'H', 'HA', 'CB', 'HB1', 'HB2', 'SG', 'HG'),
    'GLN': ('N', 'CA', 'C', 'O', 'H', 'HA', 'CB', 'HB1', 'HB2', 'CG', 'HG1', 'HG2', 'CD', 'OE1', 'NE2', 'HE21', 'HE22'),
    'GLU': ('N', 'CA', 'C', 'O', 'H', 'HA', 'CB', 'HB1', 'HB2', 'CG', 'HG1', 'HG2', 'CD', 'OE1', 'OE2'),
    'GLY': ('N', 'CA', 'C', 'O', 'H', 'HA1', 'HA2'),
    'HID': ('N', 'CA', 'C', 'O', 'H', 'HA', 'CB', 'HB1', 'HB2', 'CG', 'ND1', 'HD1', 'CE1', 'HE1', 'NE2', 'CD2', 'HD2'),
    'HIE': ('N', 'CA', 'C', 'O', 'H', 'HA', 'CB', 'HB1', 'HB2', 'CG', 'ND1', 'CE1', 'HE1', 'NE2', 'HE2', 'CD2', 'HD2'),
    'ILE': (
    'N', 'CA', 'C', 'O', 'H', 'HA', 'CB', 'HB', 'CG2', 'HG21', 'HG22', 'HG23', 'CG1', 'HG11', 'HG12', 'CD', 'HD1',
    'HD2', 'HD3'),
    'LEU': (
    'N', 'CA', 'C', 'O', 'H', 'HA', 'CB', 'HB1', 'HB2', 'CG', 'HG', 'CD1', 'HD11', 'HD12', 'HD13', 'CD2', 'HD21',
    'HD22', 'HD23'),
    'LYS': (
    'N', 'CA', 'C', 'O', 'H', 'HA', 'CB', 'HB1', 'HB2', 'CG', 'HG1', 'HG2', 'CD', 'HD1', 'HD2', 'CE', 'HE1', 'HE2',
    'NZ', 'HZ1', 'HZ2', 'HZ3'),
    'MET': ('N', 'CA', 'C', 'O', 'H', 'HA', 'CB', 'HB1', 'HB2', 'CG', 'HG1', 'HG2', 'SD', 'CE', 'HE1', 'HE2', 'HE3'),
    'PHE': (
    'N', 'CA', 'C', 'O', 'H', 'HA', 'CB', 'HB1', 'HB2', 'CG', 'CD1', 'HD1', 'CE1', 'HE1', 'CZ', 'HZ', 'CE2', 'HE2',
    'CD2', 'HD2'),
    'PRO': ('N', 'CA', 'C', 'O', 'HA', 'CB', 'HB1', 'HB2', 'CG', 'HG1', 'HG2', 'CD', 'HD1', 'HD2'),
    'SER': ('N', 'CA', 'C', 'O', 'H', 'HA', 'CB', 'HB1', 'HB2', 'OG', 'HG'),
    'THR': ('N', 'CA', 'C', 'O', 'H', 'HA', 'CB', 'HB', 'CG2', 'HG21', 'HG22', 'HG23', 'OG1', 'HG1'),
    'TRP': (
    'N', 'CA', 'C', 'O', 'H', 'HA', 'CB', 'HB1', 'HB2', 'CG', 'CD1', 'HD1', 'NE1', 'HE1', 'CE2', 'CZ2', 'HZ2', 'CH2',
    'HH2', 'CZ3', 'HZ3', 'CE3', 'HE3', 'CD2'),
    'TYR': (
    'N', 'CA', 'C', 'O', 'H', 'HA', 'CB', 'HB1', 'HB2', 'CG', 'CD1', 'HD1', 'CE1', 'HE1', 'CZ', 'OH', 'HH', 'CE2',
    'HE2', 'CD2', 'HD2'),
    'VAL': ('N', 'CA', 'C', 'O', 'H', 'HA', 'CB', 'HB', 'CG1', 'HG11', 'HG12', 'HG13', 'CG2', 'HG21', 'HG22', 'HG23'),
}

atom_alias_gromos = {}

atom_alias_amber = {
    ('ILE', 'CD1'): 'CD',

    ('GLY', 'HA2'): 'HA1',
    ('GLY', 'HA3'): 'HA2',

    # exceptions: GLY ALA ILE THR VAL
    ('ARG', 'HB2'): 'HB1', ('ARG', 'HB3'): 'HB2',
    ('ASN', 'HB2'): 'HB1', ('ASN', 'HB3'): 'HB2',
    ('ASP', 'HB2'): 'HB1', ('ASP', 'HB3'): 'HB2',
    ('CYS', 'HB2'): 'HB1', ('CYS', 'HB3'): 'HB2',
    ('HID', 'HB2'): 'HB1', ('HID', 'HB3'): 'HB2',
    ('HIE', 'HB2'): 'HB1', ('HIE', 'HB3'): 'HB2',
    ('GLN', 'HB2'): 'HB1', ('GLN', 'HB3'): 'HB2',
    ('GLU', 'HB2'): 'HB1', ('GLU', 'HB3'): 'HB2',
    ('LEU', 'HB2'): 'HB1', ('LEU', 'HB3'): 'HB2',
    ('LYS', 'HB2'): 'HB1', ('LYS', 'HB3'): 'HB2',
    ('MET', 'HB2'): 'HB1', ('MET', 'HB3'): 'HB2',
    ('PHE', 'HB2'): 'HB1', ('PHE', 'HB3'): 'HB2',
    ('PRO', 'HB2'): 'HB1', ('PRO', 'HB3'): 'HB2',
    ('SER', 'HB2'): 'HB1', ('SER', 'HB3'): 'HB2',
    ('TRP', 'HB2'): 'HB1', ('TRP', 'HB3'): 'HB2',
    ('TYR', 'HB2'): 'HB1', ('TYR', 'HB3'): 'HB2',

    ('ARG', 'HG2'): 'HG1', ('ARG', 'HG3'): 'HG2',
    ('GLN', 'HG2'): 'HG1', ('GLN', 'HG3'): 'HG2',
    ('GLU', 'HG2'): 'HG1', ('GLU', 'HG3'): 'HG2',
    ('LYS', 'HG2'): 'HG1', ('LYS', 'HG3'): 'HG2',
    ('MET', 'HG2'): 'HG1', ('MET', 'HG3'): 'HG2',
    ('PRO', 'HG2'): 'HG1', ('PRO', 'HG3'): 'HG2',

    ('ILE', 'HG12'): 'HG11',
    ('ILE', 'HG13'): 'HG12',

    ('ARG', 'HD2'): 'HD1', ('ARG', 'HD3'): 'HD2',
    ('LYS', 'HD2'): 'HD1', ('LYS', 'HD3'): 'HD2',
    ('PRO', 'HD2'): 'HD1', ('PRO', 'HD3'): 'HD2',

    ('LYS', 'HE2'): 'HE1',
    ('LYS', 'HE3'): 'HE2',

    ('ILE', 'HD11'): 'HD1',
    ('ILE', 'HD12'): 'HD2',
    ('ILE', 'HD13'): 'HD3',
}

atom_alias_ros = {
    ('GLY', 'HA2'): ('GLY', '1HA'),
    ('GLY', 'HA3'): ('GLY', '2HA'),
    ('SER', 'HB2'): ('SER', '1HB'),
    ('SER', 'HB3'): ('SER', '2HB'),
    ('HIS', 'HB2'): ('HIS', '1HB'),
    ('HIS', 'HB3'): ('HIS', '2HB'),
    ('MET', 'HB2'): ('MET', '1HB'),
    ('MET', 'HB3'): ('MET', '2HB'),
    ('MET', 'HG2'): ('MET', '1HG'),
    ('MET', 'HG3'): ('MET', '2HG'),
    ('MET', 'HE1'): ('MET', '1HE'),
    ('MET', 'HE2'): ('MET', '2HE'),
    ('MET', 'HE3'): ('MET', '3HE'),
    ('ARG', 'HB2'): ('ARG', '1HB'),
    ('ARG', 'HB3'): ('ARG', '2HB'),
    ('ARG', 'HG2'): ('ARG', '1HG'),
    ('ARG', 'HG3'): ('ARG', '2HG'),
    ('ARG', 'HD2'): ('ARG', '1HD'),
    ('ARG', 'HD3'): ('ARG', '2HD'),
    ('ARG', 'HH11'): ('ARG', '1HH1'),
    ('ARG', 'HH12'): ('ARG', '2HH1'),
    ('ARG', 'HH21'): ('ARG', '1HH2'),
    ('ARG', 'HH22'): ('ARG', '2HH2'),
    ('TYR', 'HB2'): ('TYR', '1HB'),
    ('TYR', 'HB3'): ('TYR', '2HB'),
    ('PHE', 'HB2'): ('PHE', '1HB'),
    ('PHE', 'HB3'): ('PHE', '2HB'),
    ('THR', 'HG21'): ('THR', '1HG2'),
    ('THR', 'HG22'): ('THR', '2HG2'),
    ('THR', 'HG23'): ('THR', '3HG2'),
    ('VAL', 'HG11'): ('VAL', '1HG1'),
    ('VAL', 'HG12'): ('VAL', '2HG1'),
    ('VAL', 'HG13'): ('VAL', '3HG1'),
    ('VAL', 'HG21'): ('VAL', '1HG2'),
    ('VAL', 'HG22'): ('VAL', '2HG2'),
    ('VAL', 'HG23'): ('VAL', '3HG2'),
    ('PRO', 'HB2'): ('PRO', '1HB'),
    ('PRO', 'HB3'): ('PRO', '2HB'),
    ('PRO', 'HG2'): ('PRO', '1HG'),
    ('PRO', 'HG3'): ('PRO', '2HG'),
    ('PRO', 'HD2'): ('PRO', '1HD'),
    ('PRO', 'HD3'): ('PRO', '2HD'),
    ('GLU', 'HB2'): ('GLU', '1HB'),
    ('GLU', 'HB3'): ('GLU', '2HB'),
    ('GLU', 'HG2'): ('GLU', '1HG'),
    ('GLU', 'HG3'): ('GLU', '2HG'),
    ('ILE', 'HG12'): ('ILE', '1HG1'),
    ('ILE', 'HG13'): ('ILE', '2HG1'),
    ('ILE', 'HG21'): ('ILE', '1HG2'),
    ('ILE', 'HG22'): ('ILE', '2HG2'),
    ('ILE', 'HG23'): ('ILE', '3HG2'),
    ('ILE', 'HD11'): ('ILE', '1HD1'),
    ('ILE', 'HD12'): ('ILE', '2HD1'),
    ('ILE', 'HD13'): ('ILE', '3HD1'),
    ('ALA', 'HB1'): ('ALA', '1HB'),
    ('ALA', 'HB2'): ('ALA', '2HB'),
    ('ALA', 'HB3'): ('ALA', '3HB'),
    ('ASP', 'HB2'): ('ASP', '1HB'),
    ('ASP', 'HB3'): ('ASP', '2HB'),
    ('GLN', 'HB2'): ('GLN', '1HB'),
    ('GLN', 'HB3'): ('GLN', '2HB'),
    ('GLN', 'HG2'): ('GLN', '1HG'),
    ('GLN', 'HG3'): ('GLN', '2HG'),
    ('GLN', 'HE22'): ('GLN', '1HE2'),
    ('GLN', 'HE21'): ('GLN', '2HE2'),
    ('TRP', 'HB2'): ('TRP', '1HB'),
    ('TRP', 'HB3'): ('TRP', '2HB'),
    ('LYS', 'HB2'): ('LYS', '1HB'),
    ('LYS', 'HB3'): ('LYS', '2HB'),
    ('LYS', 'HG2'): ('LYS', '1HG'),
    ('LYS', 'HG3'): ('LYS', '2HG'),
    ('LYS', 'HD2'): ('LYS', '1HD'),
    ('LYS', 'HD3'): ('LYS', '2HD'),
    ('LYS', 'HE2'): ('LYS', '1HE'),
    ('LYS', 'HE3'): ('LYS', '2HE'),
    ('LYS', 'HZ1'): ('LYS', '1HZ'),
    ('LYS', 'HZ2'): ('LYS', '2HZ'),
    ('LYS', 'HZ3'): ('LYS', '3HZ'),
    ('LEU', 'HB2'): ('LEU', '1HB'),
    ('LEU', 'HB3'): ('LEU', '2HB'),
    ('LEU', 'HD11'): ('LEU', '1HD1'),
    ('LEU', 'HD12'): ('LEU', '2HD1'),
    ('LEU', 'HD13'): ('LEU', '3HD1'),
    ('LEU', 'HD21'): ('LEU', '1HD2'),
    ('LEU', 'HD22'): ('LEU', '2HD2'),
    ('LEU', 'HD23'): ('LEU', '3HD2'),
    ('ASN', 'HB2'): ('ASN', '1HB'),
    ('ASN', 'HB3'): ('ASN', '2HB'),
    ('ASN', 'HD21'): ('ASN', '1HD2'),
    ('ASN', 'HD22'): ('ASN', '2HD2'),
    ('CYS', 'HB2'): ('CYS', '1HB'),
    ('CYS', 'HB3'): ('CYS', '2HB'),
    ('LEU', 'H1'): ('LEU', '1H'),
    ('LEU', 'H2'): ('LEU', '2H'),
    ('LEU', 'H3'): ('LEU', '3H'),
    ('ARG', 'H1'): ('ARG', '1H'),
    ('ARG', 'H2'): ('ARG', '2H'),
    ('ARG', 'H3'): ('ARG', '3H'),
    ('PHE', 'H1'): ('PHE', '1H'),
    ('PHE', 'H2'): ('PHE', '2H'),
    ('PHE', 'H3'): ('PHE', '3H'),
    ('GLU', 'H1'): ('GLU', '1H'),
    ('GLU', 'H2'): ('GLU', '2H'),
    ('GLU', 'H3'): ('GLU', '3H'),
    ('LYS', 'H1'): ('LYS', '1H'),
    ('LYS', 'H2'): ('LYS', '2H'),
    ('LYS', 'H3'): ('LYS', '3H'),
    ('MET', 'H1'): ('MET', '1H'),
    ('MET', 'H2'): ('MET', '2H'),
    ('MET', 'H3'): ('MET', '3H'),
    ('ILE', 'H1'): ('ILE', '1H'),
    ('ILE', 'H2'): ('ILE', '2H'),
    ('ILE', 'H3'): ('ILE', '3H'),
    ('TYR', 'H1'): ('TYR', '1H'),
    ('TYR', 'H2'): ('TYR', '2H'),
    ('TYR', 'H3'): ('TYR', '3H'),
    ('GLN', 'H1'): ('GLN', '1H'),
    ('GLN', 'H2'): ('GLN', '2H'),
    ('GLN', 'H3'): ('GLN', '3H'),
    ('SER', 'H1'): ('SER', '1H'),
    ('SER', 'H2'): ('SER', '2H'),
    ('SER', 'H3'): ('SER', '3H'),
    ('ASN', 'H1'): ('ASN', '1H'),
    ('ASN', 'H2'): ('ASN', '2H'),
    ('ASN', 'H3'): ('ASN', '3H'),
    ('ASP', 'H1'): ('ASP', '1H'),
    ('ASP', 'H2'): ('ASP', '2H'),
    ('ASP', 'H3'): ('ASP', '3H'),
    ('ALA', 'H1'): ('ALA', '1H'),
    ('ALA', 'H2'): ('ALA', '2H'),
    ('ALA', 'H3'): ('ALA', '3H'),
    ('HIS', 'H1'): ('HIS', '1H'),
    ('HIS', 'H2'): ('HIS', '2H'),
    ('HIS', 'H3'): ('HIS', '3H'),
    ('CYS', 'H1'): ('CYS', '1H'),
    ('CYS', 'H2'): ('CYS', '2H'),
    ('CYS', 'H3'): ('CYS', '3H'),
    ('VAL', 'H1'): ('VAL', '1H'),
    ('VAL', 'H2'): ('VAL', '2H'),
    ('VAL', 'H3'): ('VAL', '3H'),
    ('THR', 'H1'): ('THR', '1H'),
    ('THR', 'H2'): ('THR', '2H'),
    ('THR', 'H3'): ('THR', '3H'),
    ('GLY', 'H1'): ('GLY', '1H'),
    ('GLY', 'H2'): ('GLY', '2H'),
    ('GLY', 'H3'): ('GLY', '3H'),
    ('PRO', 'H1'): ('PRO', '1H'),
    ('PRO', 'H2'): ('PRO', '2H'),
    ('PRO', 'H3'): ('PRO', '3H'),
    ('TRP', 'H1'): ('TRP', '1H'),
    ('TRP', 'H2'): ('TRP', '2H'),
    ('TRP', 'H3'): ('TRP', '3H'),
}

atom_alias_ros_reverse = {v: k for k, v in atom_alias_ros.iteritems()}

# OXT was added after conversion from residue building code.
residue_bonds_noh = {
    'GLY': {'OXT': ('C',), 'C': ('CA', 'O', 'OXT'), 'O': ('C',), 'N': ('CA',), 'CA': ('N', 'C')},
    'ALA': {'OXT': ('C',), 'C': ('CA', 'O', 'OXT'), 'O': ('C',), 'N': ('CA',), 'CA': ('N', 'C', 'CB'), 'CB': ('CA',)},
    'CYS': {'OXT': ('C',), 'C': ('CA', 'O', 'OXT'), 'O': ('C',), 'N': ('CA',), 'CA': ('N', 'C', 'CB'),
            'CB': ('CA', 'SG'), 'SG': ('CB',)},
    'SER': {'OXT': ('C',), 'C': ('CA', 'O', 'OXT'), 'O': ('C',), 'N': ('CA',), 'CA': ('N', 'C', 'CB'),
            'CB': ('CA', 'OG'), 'OG': ('CB',)},
    'MET': {'OXT': ('C',), 'C': ('CA', 'O', 'OXT'), 'O': ('C',), 'N': ('CA',), 'CA': ('N', 'C', 'CB'),
            'CB': ('CA', 'CG'), 'CG': ('CB', 'SD'), 'SD': ('CG', 'CE'), 'CE': ('SD',)},
    'LYS': {'OXT': ('C',), 'C': ('CA', 'O', 'OXT'), 'O': ('C',), 'N': ('CA',), 'CA': ('N', 'C', 'CB'),
            'CB': ('CA', 'CG'), 'CG': ('CB', 'CD'), 'CD': ('CG', 'CE'), 'CE': ('CD', 'NZ'), 'NZ': ('CE',)},
    'ARG': {'OXT': ('C',), 'C': ('CA', 'O', 'OXT'), 'O': ('C',), 'N': ('CA',), 'CA': ('N', 'C', 'CB'),
            'CB': ('CA', 'CG'), 'CG': ('CB', 'CD'), 'CD': ('CG', 'NE'), 'NE': ('CD', 'CZ'), 'CZ': ('NE', 'NH1', 'NH2'),
            'NH1': ('CZ',), 'NH2': ('CZ',)},
    'GLU': {'OXT': ('C',), 'C': ('CA', 'O', 'OXT'), 'O': ('C',), 'N': ('CA',), 'CA': ('N', 'C', 'CB'),
            'CB': ('CA', 'CG'), 'CG': ('CB', 'CD'), 'CD': ('CG', 'OE1', 'OE2'), 'OE1': ('CD',), 'OE2': ('CD',)},
    'GLN': {'OXT': ('C',), 'C': ('CA', 'O', 'OXT'), 'O': ('C',), 'N': ('CA',), 'CA': ('N', 'C', 'CB'),
            'CB': ('CA', 'CG'), 'CG': ('CB', 'CD'), 'CD': ('CG', 'OE1', 'NE2'), 'OE1': ('CD',), 'NE2': ('CD',)},
    'ASP': {'OXT': ('C',), 'C': ('CA', 'O', 'OXT'), 'O': ('C',), 'N': ('CA',), 'CA': ('N', 'C', 'CB'),
            'CB': ('CA', 'CG'), 'CG': ('CB', 'OD1', 'OD2'), 'OD1': ('CG',), 'OD2': ('CG',)},
    'ASN': {'OXT': ('C',), 'C': ('CA', 'O', 'OXT'), 'O': ('C',), 'N': ('CA',), 'CA': ('N', 'C', 'CB'),
            'CB': ('CA', 'CG'), 'CG': ('CB', 'OD1', 'ND2'), 'OD1': ('CG',), 'ND2': ('CG',)},
    'LEU': {'OXT': ('C',), 'C': ('CA', 'O', 'OXT'), 'O': ('C',), 'N': ('CA',), 'CA': ('N', 'C', 'CB'),
            'CB': ('CA', 'CG'), 'CG': ('CB', 'CD1', 'CD2'), 'CD1': ('CG',), 'CD2': ('CG',)},
    'HIS': {'OXT': ('C',), 'C': ('CA', 'O', 'OXT'), 'O': ('C',), 'N': ('CA',), 'CA': ('N', 'C', 'CB'),
            'CB': ('CA', 'CG'), 'CG': ('CB', 'ND1', 'CD2'), 'ND1': ('CG', 'CE1'), 'CD2': ('CG', 'NE2'),
            'CE1': ('ND1', 'NE2'), 'NE2': ('CD2', 'CE1')},
    'PHE': {'OXT': ('C',), 'C': ('CA', 'O', 'OXT'), 'O': ('C',), 'N': ('CA',), 'CA': ('N', 'C', 'CB'),
            'CB': ('CA', 'CG'), 'CG': ('CB', 'CD1', 'CD2'), 'CD1': ('CG', 'CE1'), 'CD2': ('CG', 'CE2'),
            'CE1': ('CD1', 'CZ'), 'CE2': ('CD2', 'CZ'), 'CZ': ('CE1', 'CE2')},
    'TYR': {'OXT': ('C',), 'C': ('CA', 'O', 'OXT'), 'O': ('C',), 'N': ('CA',), 'CA': ('N', 'C', 'CB'),
            'CB': ('CA', 'CG'), 'CG': ('CB', 'CD1', 'CD2'), 'CD1': ('CG', 'CE1'), 'CD2': ('CG', 'CE2'),
            'CE1': ('CD1', 'CZ'), 'CE2': ('CD2', 'CZ'), 'CZ': ('CE1', 'CE2', 'OH'), 'OH': ('CZ',)},
    'TRP': {'OXT': ('C',), 'C': ('CA', 'O', 'OXT'), 'O': ('C',), 'N': ('CA',), 'CA': ('N', 'C', 'CB'),
            'CB': ('CA', 'CG'), 'CG': ('CB', 'CD1', 'CD2'), 'CD1': ('CG', 'NE1'), 'CD2': ('CG', 'CE2', 'CE3'),
            'NE1': ('CD1', 'CE2'), 'CE2': ('CD2', 'NE1', 'CZ2'), 'CE3': ('CD2', 'CZ3'), 'CZ3': ('CE3', 'CH2'),
            'CZ2': ('CE2', 'CH2'), 'CH2': ('CZ2', 'CZ3')},
    'VAL': {'OXT': ('C',), 'C': ('CA', 'O', 'OXT'), 'O': ('C',), 'N': ('CA',), 'CA': ('N', 'C', 'CB'),
            'CB': ('CA', 'CG1', 'CG2'), 'CG1': ('CB',), 'CG2': ('CB',)},
    'THR': {'OXT': ('C',), 'C': ('CA', 'O', 'OXT'), 'O': ('C',), 'N': ('CA',), 'CA': ('N', 'C', 'CB'),
            'CB': ('CA', 'OG1', 'CG2'), 'OG1': ('CB',), 'CG2': ('CB',)},
    'ILE': {'OXT': ('C',), 'C': ('CA', 'O', 'OXT'), 'O': ('C',), 'N': ('CA',), 'CA': ('N', 'C', 'CB'),
            'CB': ('CA', 'CG1', 'CG2'), 'CG1': ('CB', 'CD1'), 'CD1': ('CG1',), 'CG2': ('CB',)},
    'PRO': {'OXT': ('C',), 'C': ('CA', 'O', 'OXT'), 'O': ('C',), 'N': ('CA', 'CD'), 'CA': ('N', 'C', 'CB'),
            'CB': ('CA', 'CG'), 'CG': ('CB', 'CD'), 'CD': ('N', 'CG')},
}

residue_bonds_gromos = {
    'ALA': {
        'OXT': ('C',),
        'N': ('CA', 'H', 'H1', 'H2'),
        'CA': ('N', 'C', 'CB'),
        'C': ('CA', 'O', 'OXT'),
        'O': ('C',),
        'H': ('N',),
        'H1': ('N',),
        'H2': ('N',),
        'CB': ('CA',)
    },
    'ARG': {
        'OXT': ('C',),
        'N': ('CA', 'H', 'H1', 'H2'),
        'CA': ('N', 'C', 'CB'),
        'C': ('CA', 'O', 'OXT'),
        'O': ('C',),
        'H': ('N',),
        'H1': ('N',),
        'H2': ('N',),
        'CB': ('CA', 'CG'),
        'CG': ('CB', 'CD'),
        'CD': ('CG', 'NE'),
        'NE': ('CD', 'HE', 'CZ'),
        'HE': ('NE',),
        'CZ': ('NE', 'NH1', 'NH2'),
        'NH1': ('CZ', 'HH11', 'HH12'),
        'HH11': ('NH1',),
        'HH12': ('NH1',),
        'NH2': ('CZ', 'HH21', 'HH22'),
        'HH21': ('NH2',),
        'HH22': ('NH2',)
    },
    'ASN': {
        'OXT': ('C',),
        'N': ('CA', 'H', 'H1', 'H2'),
        'CA': ('N', 'C', 'CB'),
        'C': ('CA', 'O', 'OXT'),
        'O': ('C',),
        'H': ('N',),
        'H1': ('N',),
        'H2': ('N',),
        'CB': ('CA', 'CG'),
        'CG': ('CB', 'OD1', 'ND2'),
        'OD1': ('CG',),
        'ND2': ('CG', 'HD21', 'HD22'),
        'HD21': ('ND2',),
        'HD22': ('ND2',)
    },
    'ASP': {
        'OXT': ('C',),
        'N': ('CA', 'H', 'H1', 'H2'),
        'CA': ('N', 'C', 'CB'),
        'C': ('CA', 'O', 'OXT'),
        'O': ('C',),
        'H': ('N',),
        'H1': ('N',),
        'H2': ('N',),
        'CB': ('CA', 'CG'),
        'CG': ('CB', 'OD1', 'OD2'),
        'OD1': ('CG',),
        'OD2': ('CG',)
    },
    'CYS': {
        'OXT': ('C',),
        'N': ('CA', 'H', 'H1', 'H2'),
        'CA': ('N', 'C', 'CB'),
        'C': ('CA', 'O', 'OXT'),
        'O': ('C',),
        'H': ('N',),
        'H1': ('N',),
        'H2': ('N',),
        'CB': ('CA', 'SG'),
        'SG': ('CB', 'HG'),
        'HG': ('SG',)
    },
    'GLN': {
        'OXT': ('C',),
        'N': ('CA', 'H', 'H1', 'H2'),
        'CA': ('N', 'C', 'CB'),
        'C': ('CA', 'O', 'OXT'),
        'O': ('C',),
        'H': ('N',),
        'H1': ('N',),
        'H2': ('N',),
        'CB': ('CA', 'CG'),
        'CG': ('CB', 'CD'),
        'CD': ('CG', 'OE1', 'NE2'),
        'OE1': ('CD',),
        'NE2': ('CD', 'HE21', 'HE22'),
        'HE21': ('NE2',),
        'HE22': ('NE2',)
    },
    'GLU': {
        'OXT': ('C',),
        'N': ('CA', 'H', 'H1', 'H2'),
        'CA': ('N', 'C', 'CB'),
        'C': ('CA', 'O', 'OXT'),
        'O': ('C',),
        'H': ('N',),
        'H1': ('N',),
        'H2': ('N',),
        'CB': ('CA', 'CG'),
        'CG': ('CB', 'CD'),
        'CD': ('CG', 'OE1', 'OE2'),
        'OE1': ('CD',),
        'OE2': ('CD',)
    },
    'GLY': {
        'OXT': ('C',),
        'N': ('CA', 'H', 'H1', 'H2'),
        'CA': ('N', 'C'),
        'C': ('CA', 'O', 'OXT'),
        'O': ('C',),
        'H': ('N',),
        'H1': ('N',),
        'H2': ('N',)
    },
    'HID': {
        'OXT': ('C',),
        'N': ('CA', 'H', 'H1', 'H2'),
        'CA': ('N', 'C', 'CB'),
        'C': ('CA', 'O', 'OXT'),
        'O': ('C',),
        'H': ('N',),
        'H1': ('N',),
        'H2': ('N',),
        'CB': ('CA', 'CG'),
        'CG': ('CB', 'ND1', 'CD2'),
        'ND1': ('CG', 'HD1', 'CE1'),
        'HD1': ('ND1',),
        'CD2': ('CG', 'HD2', 'NE2'),
        'HD2': ('CD2',),
        'CE1': ('ND1', 'HE1', 'NE2'),
        'HE1': ('CE1',),
        'NE2': ('CD2', 'CE1'),
    },
    'HIE': {
        'OXT': ('C',),
        'N': ('CA', 'H', 'H1', 'H2'),
        'CA': ('N', 'C', 'CB'),
        'C': ('CA', 'O', 'OXT'),
        'O': ('C',),
        'H': ('N',),
        'H1': ('N',),
        'H2': ('N',),
        'CB': ('CA', 'CG'),
        'CG': ('CB', 'ND1', 'CD2'),
        'ND1': ('CG', 'CE1'),
        'CD2': ('CG', 'HD2', 'NE2'),
        'HD2': ('CD2',),
        'CE1': ('ND1', 'HE1', 'NE2'),
        'HE1': ('CE1',),
        'NE2': ('CD2', 'CE1', 'HE2'),
        'HE2': ('NE2',)
    },
    'ILE': {
        'OXT': ('C',),
        'N': ('CA', 'H', 'H1', 'H2'),
        'CA': ('N', 'C', 'CB'),
        'C': ('CA', 'O', 'OXT'),
        'O': ('C',),
        'H': ('N',),
        'H1': ('N',),
        'H2': ('N',),
        'CB': ('CA', 'CG1', 'CG2'),
        'CG1': ('CB', 'CD1'),
        'CG2': ('CB',),
        'CD1': ('CG1',)
    },
    'LEU': {
        'OXT': ('C',),
        'N': ('CA', 'H', 'H1', 'H2'),
        'CA': ('N', 'C', 'CB'),
        'C': ('CA', 'O', 'OXT'),
        'O': ('C',),
        'H': ('N',),
        'H1': ('N',),
        'H2': ('N',),
        'CB': ('CA', 'CG'),
        'CG': ('CB', 'CD1', 'CD2'),
        'CD1': ('CG',),
        'CD2': ('CG',)
    },
    'LYS': {
        'OXT': ('C',),
        'N': ('CA', 'H', 'H1', 'H2'),
        'CA': ('N', 'C', 'CB'),
        'C': ('CA', 'O', 'OXT'),
        'O': ('C',),
        'H': ('N',),
        'H1': ('N',),
        'H2': ('N',),
        'CB': ('CA', 'CG'),
        'CG': ('CB', 'CD'),
        'CD': ('CG', 'CE'),
        'CE': ('CD', 'NZ'),
        'NZ': ('CE', 'HZ1', 'HZ2', 'HZ3'),
        'HZ1': ('NZ',),
        'HZ2': ('NZ',),
        'HZ3': ('NZ',)
    },
    'MET': {
        'OXT': ('C',),
        'N': ('CA', 'H', 'H1', 'H2'),
        'CA': ('N', 'C', 'CB'),
        'C': ('CA', 'O', 'OXT'),
        'O': ('C',),
        'H': ('N',),
        'H1': ('N',),
        'H2': ('N',),
        'CB': ('CA', 'CG'),
        'CG': ('CB', 'SD'),
        'SD': ('CG', 'CE'),
        'CE': ('SD',)
    },
    'PHE': {
        'OXT': ('C',),
        'N': ('CA', 'H', 'H1', 'H2'),
        'CA': ('N', 'C', 'CB'),
        'C': ('CA', 'O', 'OXT'),
        'O': ('C',),
        'H': ('N',),
        'H1': ('N',),
        'H2': ('N',),
        'CB': ('CA', 'CG'),
        'CG': ('CB', 'CD1', 'CD2'),
        'CD1': ('CG', 'HD1', 'CE1'),
        'HD1': ('CD1',),
        'CD2': ('CG', 'HD2', 'CE2'),
        'HD2': ('CD2',),
        'CE1': ('CD1', 'HE1', 'CZ'),
        'HE1': ('CE1',),
        'CE2': ('CD2', 'HE2', 'CZ'),
        'HE2': ('CE2',),
        'CZ': ('CE1', 'CE2', 'HZ'),
        'HZ': ('CZ',)
    },
    'PRO': {
        'OXT': ('C',),
        'N': ('CA', 'H1', 'H2', 'CD'),
        'CA': ('N', 'C', 'CB'),
        'C': ('CA', 'O', 'OXT'),
        'O': ('C',),
        'H1': ('N',),
        'H2': ('N',),
        'CB': ('CA', 'CG'),
        'CG': ('CB', 'CD'),
        'CD': ('N', 'CG')
    },
    'SER': {
        'OXT': ('C',),
        'N': ('CA', 'H', 'H1', 'H2'),
        'CA': ('N', 'C', 'CB'),
        'C': ('CA', 'O', 'OXT'),
        'O': ('C',),
        'H': ('N',),
        'H1': ('N',),
        'H2': ('N',),
        'CB': ('CA', 'OG'),
        'OG': ('CB', 'HG'),
        'HG': ('OG',)
    },
    'THR': {
        'OXT': ('C',),
        'N': ('CA', 'H', 'H1', 'H2'),
        'CA': ('N', 'C', 'CB'),
        'C': ('CA', 'O', 'OXT'),
        'O': ('C',),
        'H': ('N',),
        'H1': ('N',),
        'H2': ('N',),
        'CB': ('CA', 'OG1', 'CG2'),
        'OG1': ('CB', 'HG1'),
        'HG1': ('OG1',),
        'CG2': ('CB',)
    },
    'TRP': {
        'OXT': ('C',),
        'N': ('CA', 'H', 'H1', 'H2'),
        'CA': ('N', 'C', 'CB'),
        'C': ('CA', 'O', 'OXT'),
        'O': ('C',),
        'H': ('N',),
        'H1': ('N',),
        'H2': ('N',),
        'CB': ('CA', 'CG'),
        'CG': ('CB', 'CD1', 'CD2'),
        'CD1': ('CG', 'HD1', 'NE1'),
        'HD1': ('CD1',),
        'CD2': ('CG', 'CE2', 'CE3'),
        'NE1': ('CD1', 'HE1', 'CE2'),
        'HE1': ('NE1',),
        'CE2': ('CD2', 'NE1', 'CZ2'),
        'CE3': ('CD2', 'HE3', 'CZ3'),
        'HE3': ('CE3',),
        'CZ2': ('CE2', 'HZ2', 'CH2'),
        'HZ2': ('CZ2',),
        'CZ3': ('CE3', 'HZ3', 'CH2'),
        'HZ3': ('CZ3',),
        'CH2': ('CZ2', 'CZ3', 'HH2'),
        'HH2': ('CH2',)
    },
    'TYR': {
        'OXT': ('C',),
        'N': ('CA', 'H', 'H1', 'H2'),
        'CA': ('N', 'C', 'CB'),
        'C': ('CA', 'O', 'OXT'),
        'O': ('C',),
        'H': ('N',),
        'H1': ('N',),
        'H2': ('N',),
        'CB': ('CA', 'CG'),
        'CG': ('CB', 'CD1', 'CD2'),
        'CD1': ('CG', 'HD1', 'CE1'),
        'HD1': ('CD1',),
        'CD2': ('CG', 'HD2', 'CE2'),
        'HD2': ('CD2',),
        'CE1': ('CD1', 'HE1', 'CZ'),
        'HE1': ('CE1',),
        'CE2': ('CD2', 'HE2', 'CZ'),
        'HE2': ('CE2',),
        'CZ': ('CE1', 'CE2', 'OH'),
        'OH': ('CZ', 'HH'),
        'HH': ('OH',)
    },
    'VAL': {
        'OXT': ('C',),
        'N': ('CA', 'H', 'H1', 'H2'),
        'CA': ('N', 'C', 'CB'),
        'C': ('CA', 'O', 'OXT'),
        'O': ('C',),
        'H': ('N',),
        'H1': ('N',),
        'H2': ('N',),
        'CB': ('CA', 'CG1', 'CG2'),
        'CG1': ('CB',),
        'CG2': ('CB',)
    },
}

residue_bonds_amber = {
    'ALA': {
        'OXT': ('C'),
        'N': ('CA', 'H', 'H1', 'H2'),
        'CA': ('N', 'C', 'HA', 'CB'),
        'C': ('OXT', 'CA', 'O'),
        'O': ('C'),
        'H': ('N'),
        'H1': ('N'),
        'H2': ('N'),
        'HA': ('CA'),
        'CB': ('CA', 'HB1', 'HB2', 'HB3'),
        'HB1': ('CB'),
        'HB2': ('CB'),
        'HB3': ('CB'),
    },
    'ARG': {
        'OXT': ('C'),
        'N': ('CA', 'H', 'H1', 'H2'),
        'CA': ('N', 'C', 'HA', 'CB'),
        'C': ('OXT', 'CA', 'O'),
        'O': ('C'),
        'H': ('N'),
        'H1': ('N'),
        'H2': ('N'),
        'HA': ('CA'),
        'CB': ('CA', 'HB1', 'HB2', 'CG'),
        'HB1': ('CB'),
        'HB2': ('CB'),
        'CG': ('CB', 'HG1', 'HG2', 'CD'),
        'HG1': ('CG'),
        'HG2': ('CG'),
        'CD': ('CG', 'HD1', 'HD2', 'NE'),
        'HD1': ('CD'),
        'HD2': ('CD'),
        'NE': ('CD', 'HE', 'CZ'),
        'HE': ('NE'),
        'CZ': ('NE', 'NH1', 'NH2'),
        'NH1': ('CZ', 'HH11', 'HH12'),
        'HH11': ('NH1'),
        'HH12': ('NH1'),
        'NH2': ('CZ', 'HH21', 'HH22'),
        'HH21': ('NH2'),
        'HH22': ('NH2'),
    },
    'ASN': {
        'OXT': ('C'),
        'N': ('CA', 'H', 'H1', 'H2'),
        'CA': ('N', 'C', 'HA', 'CB'),
        'C': ('OXT', 'CA', 'O'),
        'O': ('C'),
        'H': ('N'),
        'H1': ('N'),
        'H2': ('N'),
        'HA': ('CA'),
        'CB': ('CA', 'HB1', 'HB2', 'CG'),
        'HB1': ('CB'),
        'HB2': ('CB'),
        'CG': ('CB', 'OD1', 'ND2'),
        'OD1': ('CG'),
        'ND2': ('CG', 'HD21', 'HD22'),
        'HD21': ('ND2'),
        'HD22': ('ND2'),
    },
    'ASP': {
        'OXT': ('C'),
        'N': ('CA', 'H', 'H1', 'H2'),
        'CA': ('N', 'C', 'HA', 'CB'),
        'C': ('OXT', 'CA', 'O'),
        'O': ('C'),
        'H': ('N'),
        'H1': ('N'),
        'H2': ('N'),
        'HA': ('CA'),
        'CB': ('CA', 'HB1', 'HB2', 'CG'),
        'HB1': ('CB'),
        'HB2': ('CB'),
        'CG': ('CB', 'OD1', 'OD2'),
        'OD1': ('CG'),
        'OD2': ('CG'),
    },
    'CYS': {
        'OXT': ('C'),
        'N': ('CA', 'H', 'H1', 'H2'),
        'CA': ('N', 'C', 'HA', 'CB'),
        'C': ('OXT', 'CA', 'O'),
        'O': ('C'),
        'H': ('N'),
        'H1': ('N'),
        'H2': ('N'),
        'HA': ('CA'),
        'CB': ('CA', 'HB1', 'HB2', 'SG'),
        'HB1': ('CB'),
        'HB2': ('CB'),
        'SG': ('CB', 'HG'),
        'HG': ('SG'),
    },
    'GLN': {
        'OXT': ('C'),
        'N': ('CA', 'H', 'H1', 'H2'),
        'CA': ('N', 'C', 'HA', 'CB'),
        'C': ('OXT', 'CA', 'O'),
        'O': ('C'),
        'H': ('N'),
        'H1': ('N'),
        'H2': ('N'),
        'HA': ('CA'),
        'CB': ('CA', 'HB1', 'HB2', 'CG'),
        'HB1': ('CB'),
        'HB2': ('CB'),
        'CG': ('CB', 'HG1', 'HG2', 'CD'),
        'HG1': ('CG'),
        'HG2': ('CG'),
        'CD': ('CG', 'OE1', 'NE2'),
        'OE1': ('CD'),
        'NE2': ('CD', 'HE21', 'HE22'),
        'HE21': ('NE2'),
        'HE22': ('NE2'),
    },
    'GLU': {
        'OXT': ('C'),
        'N': ('CA', 'H', 'H1', 'H2'),
        'CA': ('N', 'C', 'HA', 'CB'),
        'C': ('OXT', 'CA', 'O'),
        'O': ('C'),
        'H': ('N'),
        'H1': ('N'),
        'H2': ('N'),
        'HA': ('CA'),
        'CB': ('CA', 'HB1', 'HB2', 'CG'),
        'HB1': ('CB'),
        'HB2': ('CB'),
        'CG': ('CB', 'HG1', 'HG2', 'CD'),
        'HG1': ('CG'),
        'HG2': ('CG'),
        'CD': ('CG', 'OE1', 'OE2'),
        'OE1': ('CD'),
        'OE2': ('CD'),
    },
    'GLY': {
        'OXT': ('C'),
        'N': ('CA', 'H', 'H1', 'H2'),
        'CA': ('N', 'C', 'HA1', 'HA2'),
        'C': ('OXT', 'CA', 'O'),
        'O': ('C'),
        'H': ('N'),
        'H1': ('N'),
        'H2': ('N'),
        'HA1': ('CA'),
        'HA2': ('CA'),
    },
    'HID': {
        'OXT': ('C'),
        'N': ('CA', 'H', 'H1', 'H2'),
        'CA': ('N', 'C', 'HA', 'CB'),
        'C': ('OXT', 'CA', 'O'),
        'O': ('C'),
        'H': ('N'),
        'H1': ('N'),
        'H2': ('N'),
        'HA': ('CA'),
        'CB': ('CA', 'HB1', 'HB2', 'CG'),
        'HB1': ('CB'),
        'HB2': ('CB'),
        'CG': ('CB', 'ND1', 'CD2'),
        'ND1': ('CG', 'HD1', 'CE1'),
        'HD1': ('ND1'),
        'CE1': ('ND1', 'HE1', 'NE2'),
        'HE1': ('CE1'),
        'NE2': ('CE1', 'CD2'),
        'CD2': ('CG', 'NE2', 'HD2'),
        'HD2': ('CD2'),
    },
    'HIE': {
        'OXT': ('C'),
        'N': ('CA', 'H', 'H1', 'H2'),
        'CA': ('N', 'C', 'HA', 'CB'),
        'C': ('OXT', 'CA', 'O'),
        'O': ('C'),
        'H': ('N'),
        'H1': ('N'),
        'H2': ('N'),
        'HA': ('CA'),
        'CB': ('CA', 'HB1', 'HB2', 'CG'),
        'HB1': ('CB'),
        'HB2': ('CB'),
        'CG': ('CB', 'ND1', 'CD2'),
        'ND1': ('CG', 'CE1'),
        'CE1': ('ND1', 'HE1', 'NE2'),
        'HE1': ('CE1'),
        'NE2': ('CE1', 'HE2', 'CD2'),
        'HE2': ('NE2'),
        'CD2': ('CG', 'NE2', 'HD2'),
        'HD2': ('CD2'),
    },
    'ILE': {
        'OXT': ('C'),
        'N': ('CA', 'H', 'H1', 'H2'),
        'CA': ('N', 'C', 'HA', 'CB'),
        'C': ('OXT', 'CA', 'O'),
        'O': ('C'),
        'H': ('N'),
        'H1': ('N'),
        'H2': ('N'),
        'HA': ('CA'),
        'CB': ('CA', 'HB', 'CG2', 'CG1'),
        'HB': ('CB'),
        'CG2': ('CB', 'HG21', 'HG22', 'HG23'),
        'HG21': ('CG2'),
        'HG22': ('CG2'),
        'HG23': ('CG2'),
        'CG1': ('CB', 'HG11', 'HG12', 'CD'),
        'HG11': ('CG1'),
        'HG12': ('CG1'),
        'CD': ('CG1', 'HD1', 'HD2', 'HD3'),
        'HD1': ('CD'),
        'HD2': ('CD'),
        'HD3': ('CD'),
    },
    'LEU': {
        'OXT': ('C'),
        'N': ('CA', 'H', 'H1', 'H2'),
        'CA': ('N', 'C', 'HA', 'CB'),
        'C': ('OXT', 'CA', 'O'),
        'O': ('C'),
        'H': ('N'),
        'H1': ('N'),
        'H2': ('N'),
        'HA': ('CA'),
        'CB': ('CA', 'HB1', 'HB2', 'CG'),
        'HB1': ('CB'),
        'HB2': ('CB'),
        'CG': ('CB', 'HG', 'CD1', 'CD2'),
        'HG': ('CG'),
        'CD1': ('CG', 'HD11', 'HD12', 'HD13'),
        'HD11': ('CD1'),
        'HD12': ('CD1'),
        'HD13': ('CD1'),
        'CD2': ('CG', 'HD21', 'HD22', 'HD23'),
        'HD21': ('CD2'),
        'HD22': ('CD2'),
        'HD23': ('CD2'),
    },
    'LYS': {
        'OXT': ('C'),
        'N': ('CA', 'H', 'H1', 'H2'),
        'CA': ('N', 'C', 'HA', 'CB'),
        'C': ('OXT', 'CA', 'O'),
        'O': ('C'),
        'H': ('N'),
        'H1': ('N'),
        'H2': ('N'),
        'HA': ('CA'),
        'CB': ('CA', 'HB1', 'HB2', 'CG'),
        'HB1': ('CB'),
        'HB2': ('CB'),
        'CG': ('CB', 'HG1', 'HG2', 'CD'),
        'HG1': ('CG'),
        'HG2': ('CG'),
        'CD': ('CG', 'HD1', 'HD2', 'CE'),
        'HD1': ('CD'),
        'HD2': ('CD'),
        'CE': ('CD', 'HE1', 'HE2', 'NZ'),
        'HE1': ('CE'),
        'HE2': ('CE'),
        'NZ': ('CE', 'HZ1', 'HZ2', 'HZ3'),
        'HZ1': ('NZ'),
        'HZ2': ('NZ'),
        'HZ3': ('NZ'),
    },
    'MET': {
        'OXT': ('C'),
        'N': ('CA', 'H', 'H1', 'H2'),
        'CA': ('N', 'C', 'HA', 'CB'),
        'C': ('OXT', 'CA', 'O'),
        'O': ('C'),
        'H': ('N'),
        'H1': ('N'),
        'H2': ('N'),
        'HA': ('CA'),
        'CB': ('CA', 'HB1', 'HB2', 'CG'),
        'HB1': ('CB'),
        'HB2': ('CB'),
        'CG': ('CB', 'HG1', 'HG2', 'SD'),
        'HG1': ('CG'),
        'HG2': ('CG'),
        'SD': ('CG', 'CE'),
        'CE': ('SD', 'HE1', 'HE2', 'HE3'),
        'HE1': ('CE'),
        'HE2': ('CE'),
        'HE3': ('CE'),
    },
    'PHE': {
        'OXT': ('C'),
        'N': ('CA', 'H', 'H1', 'H2'),
        'CA': ('N', 'C', 'HA', 'CB'),
        'C': ('OXT', 'CA', 'O'),
        'O': ('C'),
        'H': ('N'),
        'H1': ('N'),
        'H2': ('N'),
        'HA': ('CA'),
        'CB': ('CA', 'HB1', 'HB2', 'CG'),
        'HB1': ('CB'),
        'HB2': ('CB'),
        'CG': ('CB', 'CD1', 'CD2'),
        'CD1': ('CG', 'HD1', 'CE1'),
        'HD1': ('CD1'),
        'CE1': ('CD1', 'HE1', 'CZ'),
        'HE1': ('CE1'),
        'CZ': ('CE1', 'HZ', 'CE2'),
        'HZ': ('CZ'),
        'CE2': ('CZ', 'HE2', 'CD2'),
        'HE2': ('CE2'),
        'CD2': ('CG', 'CE2', 'HD2'),
        'HD2': ('CD2'),
    },
    'PRO': {
        'OXT': ('C'),
        'N': ('CA', 'H1', 'H2', 'CD'),
        'CA': ('N', 'C', 'HA', 'CB'),
        'C': ('OXT', 'CA', 'O'),
        'O': ('C'),
        'H1': ('N'),
        'H2': ('N'),
        'HA': ('CA'),
        'CB': ('CA', 'HB1', 'HB2', 'CG'),
        'HB1': ('CB'),
        'HB2': ('CB'),
        'CG': ('CB', 'HG1', 'HG2', 'CD'),
        'HG1': ('CG'),
        'HG2': ('CG'),
        'CD': ('N', 'CG', 'HD1', 'HD2'),
        'HD1': ('CD'),
        'HD2': ('CD'),
    },
    'SER': {
        'OXT': ('C'),
        'N': ('CA', 'H', 'H1', 'H2'),
        'CA': ('N', 'C', 'HA', 'CB'),
        'C': ('OXT', 'CA', 'O'),
        'O': ('C'),
        'H': ('N'),
        'H1': ('N'),
        'H2': ('N'),
        'HA': ('CA'),
        'CB': ('CA', 'HB1', 'HB2', 'OG'),
        'HB1': ('CB'),
        'HB2': ('CB'),
        'OG': ('CB', 'HG'),
        'HG': ('OG'),
    },
    'THR': {
        'OXT': ('C'),
        'N': ('CA', 'H', 'H1', 'H2'),
        'CA': ('N', 'C', 'HA', 'CB'),
        'C': ('OXT', 'CA', 'O'),
        'O': ('C'),
        'H': ('N'),
        'H1': ('N'),
        'H2': ('N'),
        'HA': ('CA'),
        'CB': ('CA', 'HB', 'CG2', 'OG1'),
        'HB': ('CB'),
        'CG2': ('CB', 'HG21', 'HG22', 'HG23'),
        'HG21': ('CG2'),
        'HG22': ('CG2'),
        'HG23': ('CG2'),
        'OG1': ('CB', 'HG1'),
        'HG1': ('OG1'),
    },
    'TRP': {
        'OXT': ('C'),
        'N': ('CA', 'H', 'H1', 'H2'),
        'CA': ('N', 'C', 'HA', 'CB'),
        'C': ('OXT', 'CA', 'O'),
        'O': ('C'),
        'H': ('N'),
        'H1': ('N'),
        'H2': ('N'),
        'HA': ('CA'),
        'CB': ('CA', 'HB1', 'HB2', 'CG'),
        'HB1': ('CB'),
        'HB2': ('CB'),
        'CG': ('CB', 'CD1', 'CD2'),
        'CD1': ('CG', 'HD1', 'NE1'),
        'HD1': ('CD1'),
        'NE1': ('CD1', 'HE1', 'CE2'),
        'HE1': ('NE1'),
        'CE2': ('NE1', 'CZ2', 'CD2'),
        'CZ2': ('CE2', 'HZ2', 'CH2'),
        'HZ2': ('CZ2'),
        'CH2': ('CZ2', 'HH2', 'CZ3'),
        'HH2': ('CH2'),
        'CZ3': ('CH2', 'HZ3', 'CE3'),
        'HZ3': ('CZ3'),
        'CE3': ('CZ3', 'HE3', 'CD2'),
        'HE3': ('CE3'),
        'CD2': ('CG', 'CE2', 'CE3'),
    },
    'TYR': {
        'OXT': ('C'),
        'N': ('CA', 'H', 'H1', 'H2'),
        'CA': ('N', 'C', 'HA', 'CB'),
        'C': ('OXT', 'CA', 'O'),
        'O': ('C'),
        'H': ('N'),
        'H1': ('N'),
        'H2': ('N'),
        'HA': ('CA'),
        'CB': ('CA', 'HB1', 'HB2', 'CG'),
        'HB1': ('CB'),
        'HB2': ('CB'),
        'CG': ('CB', 'CD1', 'CD2'),
        'CD1': ('CG', 'HD1', 'CE1'),
        'HD1': ('CD1'),
        'CE1': ('CD1', 'HE1', 'CZ'),
        'HE1': ('CE1'),
        'CZ': ('CE1', 'OH', 'CE2'),
        'OH': ('CZ', 'HH'),
        'HH': ('OH'),
        'CE2': ('CZ', 'HE2', 'CD2'),
        'HE2': ('CE2'),
        'CD2': ('CG', 'CE2', 'HD2'),
        'HD2': ('CD2'),
    },
    'VAL': {
        'OXT': ('C'),
        'N': ('CA', 'H', 'H1', 'H2'),
        'CA': ('N', 'C', 'HA', 'CB'),
        'C': ('OXT', 'CA', 'O'),
        'O': ('C'),
        'H': ('N'),
        'H1': ('N'),
        'H2': ('N'),
        'HA': ('CA'),
        'CB': ('CA', 'HB', 'CG1', 'CG2'),
        'HB': ('CB'),
        'CG1': ('CB', 'HG11', 'HG12', 'HG13'),
        'HG11': ('CG1'),
        'HG12': ('CG1'),
        'HG13': ('CG1'),
        'CG2': ('CB', 'HG21', 'HG22', 'HG23'),
        'HG21': ('CG2'),
        'HG22': ('CG2'),
        'HG23': ('CG2'),
    },
}

# NOTE: mainchain; N except PRO.N donates one, all O accepts two.
hbond_donors = {
    ('ARG', 'NE'): 1, ('ARG', 'NH1'): 2, ('ARG', 'NH2'): 2, ('HIS', 'ND1'): 1, ('HIS', 'NE2'): 1,
    ('ASN', 'ND2'): 2, ('GLN', 'NE2'): 2, ('LYS', 'NZ'): 3, ('SER', 'OG'): 1, ('THR', 'OG1'): 1,
    ('TRP', 'NE1'): 1, ('TYR', 'OH'): 1, ('CYS', 'SG'): 1,
}
hbond_acceptors = frozenset((
    ('ASP', 'OD1'), ('ASP', 'OD2'), ('GLU', 'OE1'), ('GLU', 'OE2'), ('HIS', 'ND1'), ('HIS', 'NE2'),
    ('MET', 'SD'), ('SER', 'OG'), ('THR', 'OG1'), ('TYR', 'OH'),
    ('ASN', 'OD1'), ('GLN', 'OE1'), ('CYS', 'SG'),
))

atom_alias = atom_alias_gromos
residue_atoms = residue_atoms_gromos
residue_bonds = residue_bonds_gromos


def convert_from_rosetta(pdb, out=None):
    new_lines = []
    with open(pdb, 'r') as fin:
        for L in fin:
            if not L.startswith('ATOM  '):
                new_lines.append(L)
                continue
            else:
                resn, atomn = L[17:20], L[12:16].strip()
                k = (resn, atomn)

                if k in atom_alias_ros_reverse:
                    resn, atomn = atom_alias_ros_reverse[(resn, atomn)]
                atomn = '%4s' % ('%-3s' % atomn)
                L = list(L)
                L[17:20] = resn
                L[12:16] = atomn
                L = ''.join(L)
            new_lines.append(L)

    if out is None:
        out = pdb

    with open(out, 'w') as fout:
        for line in new_lines:
            fout.write(line)
